
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author STELLAR
 */
public class XTSAESDialog extends javax.swing.JDialog {

    /**
     * Creates new form XTSAESDialog
     */
    public XTSAESDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputButton = new javax.swing.JButton();
        pathInputField = new javax.swing.JTextField();
        keyButton = new javax.swing.JButton();
        pathKeyField = new javax.swing.JTextField();
        outputButton = new javax.swing.JButton();
        pathOutputField = new javax.swing.JTextField();
        inputLabel = new javax.swing.JLabel();
        inputLabel1 = new javax.swing.JLabel();
        inputLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        encryptButton = new javax.swing.JButton();
        decryptButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("XTS-AES by Juan-Fajar-Iqbal");
        setResizable(false);

        inputButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        inputButton.setText("Browse..");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolInputActionPerformed(evt);
            }
        });

        pathInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathInputFieldActionPerformed(evt);
            }
        });

        keyButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        keyButton.setText("Browse..");
        keyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyButtonActionPerformed(evt);
            }
        });

        pathKeyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathKeyFieldActionPerformed(evt);
            }
        });

        outputButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        outputButton.setText("Browse..");
        outputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputButtonActionPerformed(evt);
            }
        });

        pathOutputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathOutputFieldActionPerformed(evt);
            }
        });

        inputLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        inputLabel.setText("Input File:");

        inputLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        inputLabel1.setText("Key File:");

        inputLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        inputLabel2.setText("Output File:");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XTS-AES Encryptor-Decryptor");

        encryptButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        encryptButton.setText("Encrypt");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        decryptButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        decryptButton.setText("Decrypt");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Kriptografi dan Keamanan Informasi -");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Juan Karsten, M. Fajarrizky, M.Iqbal");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText(" FASILKOM UI 2013");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputLabel2)
                            .addComponent(inputLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathOutputField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathKeyField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(keyButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputButton))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(encryptButton)
                        .addGap(43, 43, 43)
                        .addComponent(decryptButton)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputButton)
                    .addComponent(pathInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyButton)
                    .addComponent(pathKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLabel2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputButton)
                    .addComponent(pathOutputField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptButton)
                    .addComponent(decryptButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolInputActionPerformed
        final JFileChooser fc = new JFileChooser();

        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
            String pathInput = fc.getSelectedFile().getAbsolutePath();
            pathInputField.setText(pathInput);
        }

    }//GEN-LAST:event_tombolInputActionPerformed

    private void pathInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathInputFieldActionPerformed

    private void keyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyButtonActionPerformed
        final JFileChooser fc = new JFileChooser();

        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
            String pathInput = fc.getSelectedFile().getAbsolutePath();
            pathKeyField.setText(pathInput);
        }
    }//GEN-LAST:event_keyButtonActionPerformed

    private void pathKeyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathKeyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathKeyFieldActionPerformed

    private void outputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputButtonActionPerformed
        final JFileChooser fc = new JFileChooser();

        int retval = fc.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
            String pathInput = fc.getSelectedFile().getAbsolutePath();
            pathOutputField.setText(pathInput);
        }
    }//GEN-LAST:event_outputButtonActionPerformed

    private void pathOutputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathOutputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathOutputFieldActionPerformed

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        // TODO add your handling code here:
//        String input=pathInputField.getText();
//        String key=pathKeyField.getText();
//        String output=pathOutputField.getText();
//        
//        FileByteReader inputReader=new FileByteReader(input);
//        FileByteReader keyReader=new FileByteReader(key);
//        FileByteWriter outputWriter=new FileByteWriter(output);
//        
//        XTSAES xtsaes=new XTSAES();
//        byte[] P=inputReader.read();
//        byte[] keys=keyReader.read();
//        byte[] outputs=XTSUtils.unify(xtsaes.XTSAESEnc(P, keys, P.length/16+1));
//        
//        outputWriter.write(outputs);
//=======
        BufferedReader buff = null;
        try {
            // TODO add your handling code here:


            String input = pathInputField.getText();
            String key = pathKeyField.getText();
            String output = pathOutputField.getText();
            FileByteReader inputReader = new FileByteReader(input);
            FileByteReader keyReader = new FileByteReader(key);
            File file = new File(key);
            buff = new BufferedReader(new InputStreamReader(new FileInputStream(file)));
            String keyInput = buff.readLine();

            FileByteWriter outputWriter = new FileByteWriter(output);
            XTSAES xtsaes = new XTSAES();
            byte[] P = inputReader.read();
            byte[] keys = Util.hex2byte(keyInput);
            System.out.println(keys.length);
            System.out.print("wow"+keyInput+" ");
            main.printMatrix(keys);
            Result res=xtsaes.XTSAESEnc(P, keys, P.length / 16 + 1);
            byte[] outputs = XTSUtils.unify(res.getOutput(),res.getLen());
            System.out.println(outputs.length);
            outputWriter.write(outputs);
            
            inputReader = new FileByteReader(output);
            System.out.println("test test"+inputReader.read().length);
        } catch (IOException ex) {
            Logger.getLogger(XTSAESDialog.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                buff.close();
            } catch (IOException ex) {
                Logger.getLogger(XTSAESDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        try {
            // TODO add your handling code here:
            BufferedReader reBuff = null;

            String inputDec = pathInputField.getText();
            String keyDec = pathKeyField.getText();
            String outputDec = pathOutputField.getText();

            FileByteReader inputReader = new FileByteReader(inputDec);
            FileByteReader keyReader = new FileByteReader(keyDec);
            FileByteWriter outputWriter = new FileByteWriter(outputDec);

            //System.out.println("test test dec"+inputReader.read().length);
            File fileDec = new File(keyDec);
            reBuff = new BufferedReader(new InputStreamReader(new FileInputStream(fileDec)));
            String keyInputDec = reBuff.readLine();

            XTSAES xtsaes = new XTSAES();
            byte[] PDec = inputReader.read();
            byte[] keysDec = Util.hex2byte(keyInputDec);
            System.out.println(PDec.length);
            System.out.print("wow"+keyInputDec+" ");
            main.printMatrix(keysDec);
            Result res=xtsaes.XTSAESDec(PDec, keysDec, PDec.length / 16 + 1);
            byte[] outputsDec = XTSUtils.unify(res.getOutput(),res.getLen());
            outputWriter.write(outputsDec);
        } catch (IOException ex) {
            Logger.getLogger(XTSAESDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_decryptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XTSAESDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XTSAESDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XTSAESDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XTSAESDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                XTSAESDialog dialog = new XTSAESDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decryptButton;
    private javax.swing.JButton encryptButton;
    private javax.swing.JButton inputButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JLabel inputLabel1;
    private javax.swing.JLabel inputLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton keyButton;
    private javax.swing.JButton outputButton;
    private javax.swing.JTextField pathInputField;
    private javax.swing.JTextField pathKeyField;
    private javax.swing.JTextField pathOutputField;
    // End of variables declaration//GEN-END:variables
}
